"""empty message

Revision ID: 847fe0804c14
Revises: 5ec4ab7f9dfd
Create Date: 2026-01-07 22:27:37.174394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847fe0804c14'
down_revision = '5ec4ab7f9dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
